"use client";

import { useState, useEffect, useCallback } from "react";
import { Card, CardContent, CardHeader } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Progress } from "@/components/ui/Progress";
import { Heart, ArrowLeft, ArrowRight, Save, CheckCircle, Shield } from "lucide-react";
import Link from "next/link";

interface Question {
  id: string;
  text: string;
  type: "radio" | "text" | "multiselect";
  options?: { value: string; label: string }[];
  section: string;
  sectionIndex: number;
  sensitive?: boolean;
}

// All 264 questions organized by section
const allQuestions: Question[] = [
  // Section 1: Core Identity (20 questions)
  { id: "ci1", text: "What is your full name?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci2", text: "What name do you prefer to be called professionally?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci3", text: "What name do you prefer to be called personally?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci4", text: "Are there any nicknames, titles, or relational names that matter to you?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci5", text: "What pronouns do you use?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci6", text: "Where are you based?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci7", text: "What communities, cultures, regions, or life experiences have shaped how you see the world?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci8", text: "How do you currently describe who you are in one sentence?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci9", text: "How do you wish people understood who you are beyond your title?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci10", text: "What parts of your identity feel most central to your work?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci11", text: "What season of life are you currently in?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci12", text: "What are you learning right now?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci13", text: "What are you releasing right now?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci14", text: "What are you building right now?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci15", text: "What feels newly clear to you?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci16", text: "What feels unfinished or still becoming?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci17", text: "What has changed in you over the last 12 months?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci18", text: "What are you no longer willing to carry?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci19", text: "What are you finally ready to say out loud?", type: "text", section: "Core Identity", sectionIndex: 1 },
  { id: "ci20", text: "What words would you use to describe this chapter of your life?", type: "text", section: "Core Identity", sectionIndex: 1 },

  // Section 2: Origin Story (34 questions)
  { id: "os1", text: "What were you like as a child?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os2", text: "What did people often notice about you when you were young?", type: "text", section: "Origin Story", sectionIndex: 2 },
  { id: "os3", text: "What did you love before the world told you what was practical?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os4", text: "What did you understand early that other people seemed to miss?", type: "text", section: "Origin Story", sectionIndex: 2 },
  { id: "os5", text: "What did you have to become good at in order to survive, belong, succeed, or be loved?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os6", text: "What role did you often play in your family or community? (caretaker, achiever, rebel, peacekeeper, invisible one, truth-teller, fixer, performer, observer, or something else?)", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os7", text: "What did you learn too early?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os8", text: "What did you have to unlearn later?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os9", text: "What part of your younger self still walks with you in your work today?", type: "text", section: "Origin Story", sectionIndex: 2 },
  { id: "os10", text: "What are the major life events that shaped who you are?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os11", text: "Which experiences broke something open in you?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os12", text: "Which experiences refined you?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os13", text: "Which experiences gave you wisdom you could not have learned any other way?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os14", text: "What losses have shaped your worldview?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os15", text: "What victories have shaped your confidence?", type: "text", section: "Origin Story", sectionIndex: 2 },
  { id: "os16", text: "What betrayals, disappointments, or disruptions changed your standards?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os17", text: "What moments taught you resilience?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os18", text: "What moments taught you surrender?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os19", text: "What moments taught you discernment?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os20", text: "What moments taught you that your work mattered?", type: "text", section: "Origin Story", sectionIndex: 2 },
  { id: "os21", text: "What experiences do you rarely talk about but know deeply shaped you?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os22", text: "Are there stories you are comfortable sharing publicly?", type: "text", section: "Origin Story", sectionIndex: 2 },
  { id: "os23", text: "Are there stories that are only for private context and should not be used publicly?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os24", text: "Are there stories that should never be referenced by AI-generated content?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os25", text: "Was there a specific moment when your life or work changed direction?", type: "text", section: "Origin Story", sectionIndex: 2 },
  { id: "os26", text: "What happened?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os27", text: "What did that moment require from you?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os28", text: "What did it reveal?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os29", text: "What did you lose?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os30", text: "What did you gain?", type: "text", section: "Origin Story", sectionIndex: 2 },
  { id: "os31", text: "What did you finally understand?", type: "text", section: "Origin Story", sectionIndex: 2 },
  { id: "os32", text: "What did you stop pretending?", type: "text", section: "Origin Story", sectionIndex: 2, sensitive: true },
  { id: "os33", text: "What did you decide from that moment forward?", type: "text", section: "Origin Story", sectionIndex: 2 },
  { id: "os34", text: "How does that turning point still inform your work today?", type: "text", section: "Origin Story", sectionIndex: 2 },

  // Section 3: Calling, Purpose, and Sacred Why (23 questions)
  { id: "cp1", text: "Why do you do the work you do?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp2", text: "What problem can you not unsee?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp3", text: "What pain in the world keeps calling your attention?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp4", text: "What transformation do you feel uniquely assigned to help others experience?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp5", text: "Who are you here to serve?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp6", text: "Why do those people matter to you?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp7", text: "What do you believe is possible for them that they may not yet believe for themselves?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp8", text: "What do you want people to feel in your presence?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp9", text: "What do you want people to remember after working with you?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp10", text: "What would still matter to you even if no one applauded?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp11", text: "What is your current mission?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp12", text: "What mission have you outgrown?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp13", text: "What mission is emerging?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp14", text: "What do you believe your work is really about beneath the surface?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp15", text: "What is the deeper transformation underneath your visible offer or service?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp16", text: "What did success used to mean that no longer fits?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp17", text: "What does aligned success feel like in your body, schedule, relationships, and work?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp18", text: "What would success look like if it were quiet, sustainable, and deeply true?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp19", text: "What metrics matter to you?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp20", text: "What metrics do not matter as much as people think they should?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp21", text: "What are you unwilling to sacrifice for success?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3, sensitive: true },
  { id: "cp22", text: "What kind of success would feel hollow?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },
  { id: "cp23", text: "What kind of success would feel holy, grounded, meaningful, or complete?", type: "text", section: "Calling, Purpose, and Sacred Why", sectionIndex: 3 },

  // Section 4: Values and Standards (30 questions)
  { id: "vs1", text: "What are your top 5 to 10 core values?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs2", text: "For each value, what does it mean to you specifically?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs3", text: "How do those values show up in your work?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs4", text: "How do those values show up in your relationships?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs5", text: "Which value do you protect most fiercely?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs6", text: "Which value has cost you something?", type: "text", section: "Values and Standards", sectionIndex: 4, sensitive: true },
  { id: "vs7", text: "Which value did you have to fight to reclaim?", type: "text", section: "Values and Standards", sectionIndex: 4, sensitive: true },
  { id: "vs8", text: "Which value do people often misunderstand in you?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs9", text: "Which value do you want your clients to embody more fully?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs10", text: "What values should your AI always reflect when creating in your voice?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs11", text: "What are your personal non-negotiables?", type: "text", section: "Values and Standards", sectionIndex: 4, sensitive: true },
  { id: "vs12", text: "What are your professional non-negotiables?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs13", text: "What are your relational non-negotiables?", type: "text", section: "Values and Standards", sectionIndex: 4, sensitive: true },
  { id: "vs14", text: "What are your spiritual, ethical, or moral non-negotiables?", type: "text", section: "Values and Standards", sectionIndex: 4, sensitive: true },
  { id: "vs15", text: "What will you no longer tolerate?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs16", text: "What will you no longer over-explain?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs17", text: "What will you no longer shrink to preserve?", type: "text", section: "Values and Standards", sectionIndex: 4, sensitive: true },
  { id: "vs18", text: "What boundaries are essential for your health, peace, energy, or integrity?", type: "text", section: "Values and Standards", sectionIndex: 4, sensitive: true },
  { id: "vs19", text: "What do people need to understand before working closely with you?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs20", text: "What should your AI never recommend, imply, or create on your behalf?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs21", text: "What does integrity mean to you?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs22", text: "How do you know when something is out of alignment?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs23", text: "What compromises are dangerous for you?", type: "text", section: "Values and Standards", sectionIndex: 4, sensitive: true },
  { id: "vs24", text: "What kinds of shortcuts do you refuse to take?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs25", text: "What kinds of marketing, sales, leadership, or communication tactics do you reject?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs26", text: "What does ethical influence look like to you?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs27", text: "What does manipulation look like to you?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs28", text: "What does trust require?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs29", text: "What damages trust?", type: "text", section: "Values and Standards", sectionIndex: 4 },
  { id: "vs30", text: "What restores trust?", type: "text", section: "Values and Standards", sectionIndex: 4 },

  // Section 5: Beliefs and Worldview (35 questions)
  { id: "bw1", text: "What do you believe about people?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw2", text: "What do you believe about transformation?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw3", text: "What do you believe about healing, growth, change, or becoming?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw4", text: "What do you believe about suffering?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5, sensitive: true },
  { id: "bw5", text: "What do you believe about resilience?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw6", text: "What do you believe about responsibility?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw7", text: "What do you believe about purpose?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw8", text: "What do you believe about faith, spirituality, meaning, or inner guidance?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw9", text: "What do you believe about leadership?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw10", text: "What do you believe about love?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw11", text: "What do you believe about fear?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw12", text: "What do you believe about failure?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw13", text: "What do you believe about success?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw14", text: "What do you believe people often get wrong about your area of work?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw15", text: "What truth do you wish more people were brave enough to live?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw16", text: "What do you believe that goes against common advice in your industry?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw17", text: "What popular belief do you disagree with?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw18", text: "What phrase, trend, or framework makes you inwardly roll your eyes?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw19", text: "What are people oversimplifying?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw20", text: "What are people overcomplicating?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw21", text: "What are people avoiding?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw22", text: "What are people calling strategy that is actually fear?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw23", text: "What are people calling wisdom that is actually resignation?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw24", text: "What are people calling kindness that is actually self-abandonment?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw25", text: "What is one truth you would say even if it made the room uncomfortable?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw26", text: "Do you have a spiritual, religious, philosophical, or metaphysical foundation that shapes your work?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw27", text: "What language feels aligned when describing this foundation?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw28", text: "What language feels inaccurate, performative, or off-limits?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw29", text: "Are there sacred texts, teachers, traditions, or practices that influence you?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw30", text: "How should those influences be referenced?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw31", text: "Are there any beliefs you want clearly included in your soul.md?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw32", text: "Are there any beliefs you want handled gently or privately?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5, sensitive: true },
  { id: "bw33", text: "Are there any spiritual claims your AI should avoid making?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw34", text: "What role does intuition, prayer, discernment, inner wisdom, or contemplation play in your decisions?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },
  { id: "bw35", text: "How do you distinguish true guidance from fear, ego, urgency, or pressure?", type: "text", section: "Beliefs and Worldview", sectionIndex: 5 },

  // Section 6: Voice and Communication Style (30 questions)
  { id: "vc1", text: "How do you naturally speak when you are relaxed?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc2", text: "How do you sound when you are teaching?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc3", text: "How do you sound when you are encouraging someone?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc4", text: "How do you sound when you are lovingly confronting someone?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc5", text: "How do you sound when you are angry but grounded?", type: "text", section: "Voice and Communication Style", sectionIndex: 6, sensitive: true },
  { id: "vc6", text: "How do you sound when you are moved emotionally?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc7", text: "How do you sound when you are speaking from conviction?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc8", text: "What words or phrases do you use often?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc9", text: "What words or phrases would people recognize as \"so you\"?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc10", text: "What do people often say about the way you communicate?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc11", text: "Which tones feel most natural to you? (warm, direct, poetic, grounded, fierce, tender, strategic, spiritual, humorous, etc.)", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc12", text: "Which tones feel inauthentic or forced?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc13", text: "How do you want people to feel when they read your words?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc14", text: "What kind of language feels too corporate or cold?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc15", text: "What kind of language feels too casual or unprofessional?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc16", text: "What kind of language feels too trendy or performative?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc17", text: "What kind of language feels timeless and true?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc18", text: "How do you balance authority with humility?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc19", text: "How do you balance clarity with nuance?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc20", text: "How do you challenge without shaming?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc21", text: "How do you comfort without bypassing?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc22", text: "How do you inspire without hyping?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc23", text: "How do you teach without lecturing?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc24", text: "How do you sell without manipulating?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc25", text: "How do you lead without dominating?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc26", text: "How do you hold space without disappearing?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc27", text: "How do you show up fully without performing?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc28", text: "How do you stay accessible without diluting your message?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc29", text: "How do you stay sharp without becoming harsh?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },
  { id: "vc30", text: "How do you stay open without becoming vague?", type: "text", section: "Voice and Communication Style", sectionIndex: 6 },

  // Section 7: Emotional Texture and Presence (27 questions)
  { id: "et1", text: "What emotions are you comfortable expressing?", type: "text", section: "Emotional Texture and Presence", sectionIndex: 7 },
  { id: "et2", text: "What emotions do you tend to hold back?", type: "text", section: "Emotional Texture and Presence", sectionIndex: 7, sensitive: true },
  { id: "et3", text: "What emotions show up most in your work?", type: "text", section: "Emotional Texture and Presence", sectionIndex: 7 },
  { id: "et4", text: "What emotions do you help others navigate?", type: "text", section: "Emotional Texture and Presence", sectionIndex: 7 },
  { id: "et5", text: "What emotions signal that something is misaligned?", type: "text", section: "Emotional Texture and Presence", sectionIndex: 7 },
  { id: "et6", text: "What emotions signal that something is deeply right?", type: "text", section: "Emotional Texture and Presence", sectionIndex: 7 },
  { id: "et7", text: