// What the AI assistant always knows about the Command Suite itself: what exists and where, so it can point a
// client to the right place without waiting for a how-to question to match the Help library. Kept short and
// factual. UPDATE THIS whenever a feature ships or changes (Babs's rule: every "save" also updates the AI assistant).
// For step-by-step answers the assistant uses the Help library (src/lib/knowledgeBase.ts).
export const APP_MAP = `The left menu has sections: DAILY OPERATIONS (Executive Home, Daily Compass, Content Calendar, Tasks, Accountability Partner, Quick Capture, The Collective), CLIENTS & SALES (Contacts with Forms and Email sending, Pipeline, Outreach Pipelines, Calendars/booking, Campaigns & Broadcasts, Invite Tracker, Affiliates, Short Links), PLANNING & NUMBERS (Weekly Review, Goal Ladder, Planning Hub, Forecasting, Finance), GROWTH (Offers & Packages, Sales Plan, Marketing Plan, Testimonials, Website Review), ALIGNMENT (Business Alignment, Alignment Profile assessments, Progress, Business Plan, Segments), SYSTEMS (Operations, Playbook & SOPs, Legal & Compliance, Settings), GETTING STARTED (Set up Suite, First 30 Days, Starter Guide), and MY PAGES (pages the client or their assistant adds). Clients can drag sections and pages into their own order; it is saved to their account.
Scores: every score (overall health, each of the 12 dimensions, the Quick Pulse result) uses four phases: Survival 0-40, Growth 41-60, Expansion 61-80, Legacy 81-100. The 8 operational pillars on the Operations page are scored by the Suite from the client's answers and activity, not set by hand. After the three assessments (Brain, Soul, Profit) the client gets a Growth Roadmap on Business Alignment.
Assistant: the client can pop the assistant out so it floats over any page; its conversation stays on the card (newest first); New conversation saves the old one under Past conversations; Teach notes in Settings are its long-term memory about the client. It can prepare changes (contacts and tags, tasks, outreach pipelines and deals, email DRAFTS, Content Calendar posts, custom pages including deleting them, saving lasting facts) that the client approves, edits or cancels; it never sends or schedules email and never publishes right now.
Email: the client connects their own free Resend account (Full access key), verifies their own domain, and sets the sender in Contacts > Email sending; nothing is emailed to their contacts until that is done.
Social posting: the Content Calendar publishes through PostStream. LC Beacon (beacon.lccommandsuite.com) is LifeCharter's own new posting app, live for AmiLynne only; clients move to it later and will be told ahead of time.
Money: the Financial Pulse card on Executive Home has Income and Expense buttons to add entries without leaving the page, and its title opens the full Financial Pulse page (Finance > Cash Flow Dashboard). Income goals (weekly, monthly, yearly) are set in Finance > Budget.
Support: the lifebuoy icon opens Contact Support (reply within 24 hours on business days, Monday to Friday 9am to 5pm Mountain; VIP members 4 hours and an urgent text/WhatsApp line), with What's New and Recently answered. Command Suite Office Hours is the live tech call (Thursdays 11am Mountain). The Starter Guide is a step-by-step setup checklist.`;
